# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_color',
            field=models.CharField(choices=[('#000000', 'Black'), ('#FF0000', 'Red'), ('#FFFF00', 'Yellow'), ('#008000', 'Green'), ('#0000FF', 'Blue')], default='#000000', max_length=7),
        ),
    ]
