# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_choice_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_color',
            field=models.CharField(max_length=7),
        ),
    ]
