# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170316_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
